{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
{{- if .Values.ingress.ssl.enabled }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
{{- end }}
spec:
{{- if .Values.ingress.ssl.enabled }}
  tls:
  - hosts:
    - "{{ .Values.ingress.host }}"
    secretName: {{ template "fullname" . }}-tls
{{- end }}
  rules:
  - host: '{{ .Values.ingress.host }}'
    http:
      paths:
      - path: '{{ .Values.ingress.path }}'
        backend:
          serviceName: '{{ template "fullname" . }}'
          servicePort: {{ .Values.service.http.externalPort }}

{{- end }}
